### ISSUE TITLE
请补充介绍

### ISSUE THREAD

**Issue by leavez** [tripleCC/cocoapods-tdfire-binary#13]
虽然后面写了很详细的用法，但看了半天并没有理解它是做什么的。

另外，很巧的是，我和作者在类似的时间里写了一个类似插件，https://github.com/leavez/cocoapods-binary

**Comment by tripleCC** [comment]
@leavez  我稍微看了下你的代码

说下我这个插件和你不同的地方吧

你的插件是在 pod install 时，把组件编译成二进制，然后在后续的 install / update 时，直接用那次编译生成的二进制组件 （PS ：CocoaPods 在 1.3.1 后的版本，增加了类似[增量编译的功能 ](http://blog.cocoapods.org/CocoaPods-1.3.0/)，在首次 install / update  之后，后面再进行 install / update 操作，会根据更改结果进行增量编译，所以我在做这个插件时感觉针对 “非首次 install / update 后的编译” 优化，并不是必须的，因为 CocoaPods 已经帮我们做好了）

在我的方案里，二进制组件是提前编译打包好了的，然后以 zip 的形式储存在一个二进制服务器上。当我执行 install 的时候，插件设置的 `pre_command` 会去下载对应的二进制 zip 包 （这里我是手工修改的 podspec，去配置下载操作；看了你的代码是 hook 的 `resolve_dependencies` 方法，我对 ruby 不是非常熟悉，所以当初没想这样做，不过这种方式挺好，不用手工改 podspec ，到时候试试看），这样就省去了首次编译时间 （这对打包时间有优化，对需要频繁更新代码的提测阶段，有比较积极的意义。同时在 CocoaPods 添加了增量功能后，我觉得优化打包时间，是实施二进制化性价比最高的动机了）。当然，这需要多维护一个二进制服务器，以及对应的二进制版本，在组件/代码不多时，做这件事情费时费力，还收效甚微，不过针对我们团队 App 20+ 的打包时间，并且还在不断上升中的情况，费这点精力还是值得的。

上面就是这个插件和你的主要区别。

其他的和你的很像，比如我可以使用 `tdfire_use_source_pods` 对特定组件进行源码/二进制切换 ，`tdfire_use_binary!` 全局切换，你则是通过 `all_binary!`，以及 hook 原生 `pod` DSL 的处理实现相似的功能。

**Comment by CreatorMetaSky** [comment]
学习了。
